### ISSUE TITLE
php7 compatiblity

### ISSUE THREAD

**Issue by stAn47** [joomla-framework/string#17]
### Steps to reproduce the issue
hello, i am trying to get codeception and composer to work but this class is not compatible with php7 since it uses "String" as the name of the class. 

is there any solution how to make the composer and codeception run on php7 without dependency on this package? 

it would be also nice to update all other refrences and versions at: 
https://github.com/joomla/joomla-cms/blob/staging/composer.json

i am new to this area, so i won't be of much help yet. 

thanks, stan

**Comment by mbabker** [comment]
As of the 1.3.0 release of this package, there is a `StringHelper` class replacing the older `String` class.  Use that instead.  The older class is deprecated and removed in 2.0.

**Comment by stAn47** [comment]
hello, thanks, i resolved this by running additional: 

composer update joomla/string  (updated from 1.3.1 to 1.4.1)
composer update joomla/filter   (updated from 1.1.5 to 1.3.0)

and now the site can run on php7 even though the composer did not download the very latest versions of the packages. maybe the core joomla should include the composer.json files in /libraries/vendor/joomla/PACKAGE/composer.json as well, so it always runs on the latest. 

i think the problem is caused by composer not recognizing original packages in core joomla (3.6.5) and once the composer is initialized it downgrades the packages to the minimum versions. manually overwritting the libraries/vendor/joomla from the core package breaks the installation as well. 

best regards, stan

**Comment by stAn47** [comment]
pls do not mark this "closed" if you did not try the composer: 
1. install clean joomla
2. install a 3rd party package that uses joomla: 
composer require codeception/codeception --dev
3. visit the site with php7

stan

**Comment by mbabker** [comment]
The issue isn't with this independent package, hence the reason this is closed here.  What you're trying to do actually isn't supported by the distributed Joomla application; the composer.json and composer.lock files aren't distributed as part of the package and we deliberately strip non-production assets from the vendor directory in the CMS app.
