### ISSUE TITLE
Prevent "overhead" of data

### ISSUE THREAD

**Issue by jfusion** [joomla-framework/string#4]
Hello, not sure if there should be a better place to talk about this.

anyhow it goes for all the repos.. (i think, tho i have not looked at all of them..)

http://stackoverflow.com/questions/17049313/how-to-ignore-directories-with-composer

Given that there are no ways to do this in composer, could this workaround be added? normally development would not be using composer anyway and the so if the testing code could be excluded that would be nice.

----- quote from above link -----

When you run the update or install command with --prefer-dist, Composer tries to download the archive on github. You can remove the test directory from the archives by putting this in a .gitattributes file in the root directory of your project:

Tests/ export-ignore
## Composer will only use the tags on github. Just temporary remove the tests directory when creating a tag will also do the trick.

if i should raice this in another way/location let me know.

-Thanks

**Comment by nibra** [comment]
See pull request [http#31](https://github.com/joomla-framework/http/pull/31)
